version: '3'
services:
    db:
        image: postgres:14.2
        tty: true
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: db_database
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: db_password
        volumes:
            - ./docker/db:/var/lib/postgresql/data
