version: '3'
services:
    db:
        image: postgres:14.2
        tty: true
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: db_database
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: db_password
        volumes:
            - ./docker/db:/var/lib/postgresql/data
    backend:
        build:
            context: ./packages/backend/
            dockerfile: Dockerfile
        restart: always
        environment:
            CONFIG_ENV: production
        volumes:
            - ./data:/app/data
    http:
        build:
            context: ./packages/frontend/
            dockerfile: Dockerfile
        restart: always
        ports:
            - '80:80'
        environment:
            BACKEND_UPSTREAM: "server backend:3000;"
